name: Download, Sign and upload windows release
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - run: ./deploy/codesign/codesign.ps1
        shell: pwsh
        env:
          CHOCO_TOKEN: ${{ secrets.CHOCO_TOKEN }}